### ISSUE TITLE
Polar decomposition of rectangular matrices computed incorrectly 

### ISSUE THREAD

**Issue by mwojnowicz** [weijianzhang/PolarFact.jl#1]
#Here I create a 10x2 matrix.
[B[i,j]=i+j for i in 1:10, j in 1:2]

#We can construct the U factor from the singular value decomposition.  (If svd(B)=WDV', then U=WV')
W,D,V=svd(B)
Utrue=W*V'

#But this doesn't match the U factor computed by the PolarFact Package.  In fact, the dimensionality is #wrong (the output is 2x2 rather than 10x2)
using PolarFact
r=polarfact(B)
Upackage=r.U

**Comment by weijianzhang** [comment]
Thanks for letting me know. I will look into it.

**Comment by weijianzhang** [comment]
Newton's method and other iteration methods are only implemented for the square matrix case. 
If a matrix `A` has more rows than columns, we compute a QR factorization on `A = QR` and compute the polar decomposition on `R`.
See https://github.com/weijianzhang/PolarFact.jl/blob/master/src/PolarFact.jl#L35

But this is not the case for the SVD method (thanks for pointing it out!). I just fixed the svd method.
Now we have 
```julia
julia> [B[i,j] = i+j for i in 1:10, j in 1:2]
julia> polarfact(B, alg = :svd)
PolarFact.SVDResult{Float64}(10x2 Array{Float64,2}:
 -0.363256   0.46206 
 -0.259332   0.425713
 -0.155409   0.389366
 -0.0514853  0.353018
  0.0524381  0.316671
  0.156362   0.280324
  0.260285   0.243976
  0.364208   0.207629
  0.468132   0.171282
  0.572055   0.134934,2x2 Array{Float64,2}:
 15.3597  16.4037
 16.4037  19.3886)
```
